### ISSUE TITLE
Name choice

### ISSUE THREAD

**Issue by mossblaser** [SpiNNakerManchester/DataSpecification#2]
I realise this is perhaps a rather cosmetic issue but it seems that this module would be deserving of a more appropriate name. My reasoning as follows:

* Since these modules will all become part of end-users' Python installations names should probably avoid being too vague to ensure they don't conflict with existing libraries.
* DataAllocation does not imply just how specific this tool is to SpiNNaker
* This tool isn't useful because it *allocates* data, it is useful because it *compresses* data (i.e. allows it to be represented just by a specification which is more compact than the data itself).

To be a little more constructive, some suggestions:

* `spinnaker_data_spec`
* `spinnaker_data_spec_format`
* `spinnaker_data_expander`

**Comment by alan-stokes** [comment]
ive moved this issue to https://github.com/SpiNNakerManchester/sPyNNaker/issues/48
