### ISSUE TITLE
reserving the same region twice causes issues

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/DataSpecification#86]
doing so does not flag a dsg/dse error. but causes a recording error as dse will just accum the sizes. 

This only works when you dont fill in any of the region between the 2 calls of the reserve. 

replacing this in dse_functions line 152 would solve it

if self._mem_regions[region] is not None:

**Comment by dkfellows** [comment]
DSG ought to blow up if the region is reserved twice; that's almost certainly an error every time.

**Comment by dkfellows** [comment]
Currently in DSG, `reserve_memory_region` will blow up if called twice with the same memory region ID. The underlying collection of memory region “slots” (not Python slots) is a fixed size list initialised to all `None`; when a region is allocated, it's slot is filled in with a `_MemSlot` instance, which is like a glorified tuple, and if the slot was previously occupied you get a `RegionInUseException`. (`free_memory_region` puts `None` in again, but I don't think we ever call that outside of tests.) It does _not_ accumulate sizes! I can't find any record of it ever having not thrown exceptions on double-allocation of a region.

DSE assumes that the code it is running is correct. It doesn't check. It's always worked like that.
